[package]
authors = ["Remi Lafage <remi.lafage@onera.fr>"]
name = "cobyla"
version = "0.1.0"
edition = "2018"
license-file = "LICENSE.md"
description = "Rust wrapping of a C implementation of the COBYLA optimizer."
readme = "README.md"
repository = "https://github.com/relf/cobyla/"
build = "build.rs"
keywords = ["optimizer", "optimization", "constrained", "derivative-free"]
categories = ["algorithms", "api-bindings", "science"]
documentation = "https://docs.rs/cobyla"

[build-dependencies]
bindgen = "0.56.0"
cmake = "0.1"